# Generated by Django 5.1.3 on 2024-11-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_task_usertask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referred_count',
        ),
    ]
