# Generated by Django 5.1.3 on 2024-11-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_referral_code_profile_referred_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_amaount', models.PositiveBigIntegerField()),
            ],
        ),
    ]
