# Generated by Django 5.1.3 on 2024-11-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_user_withdraw_delete_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_withdraw',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
